version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
      - ./mounts/data:/var/rcloner/data:rw
      - ./mounts/logs:/var/rcloner/logs:rw
    command: npm run dev
    ports:
      - "3000:8080"
    environment:
      PORT: 8080
      NODE_ENV: development